debug: false
spring:
  redis:
    database: 3
    host: xxx
    port: 6379
    password: xxx
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        min-idle: 0
        max-idle: 8

  # datasource
  datasource:
    url: 'jdbc:mysql://xxx:3306/template?tcpKeepAlive=true&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8'
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 7200000
      idle-timeout: 1800000
      minimum-idle: 5

springdoc:
  api-docs:
    enabled: false

knife4j:
  enable: false
  production: true

## app内配置
app:
  token:
    timeout: 14400
  cache:
    key-prefix: "app:"