debug: true
spring:
  redis:
    database: 8
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000ms
        min-idle: 0
        max-idle: 8

  # datasource
  datasource:
    url: 'jdbc:mysql://172.29.91.60:3306/template?tcpKeepAlive=true&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8'
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 7200000
      idle-timeout: 1800000
      minimum-idle: 5

## app内配置
app:
  token:
    timeout: 14400
  cache:
    key-prefix: "app-uat:"